USE GD1C2024
GO

INSERT INTO EL_DROPEO.Marca(nombre)
SELECT DISTINCT PRODUCTO_MARCA
FROM gd_esquema.Maestra
WHERE PRODUCTO_MARCA IS NOT NULL

INSERT INTO EL_DROPEO.Categoria(nombre)
SELECT DISTINCT PRODUCTO_CATEGORIA
FROM gd_esquema.Maestra
WHERE PRODUCTO_CATEGORIA IS NOT NULL

INSERT INTO EL_DROPEO.Sub_Categoria(nombre, categoria_id)
SELECT DISTINCT PRODUCTO_SUB_CATEGORIA, C.id
FROM gd_esquema.Maestra
LEFT JOIN EL_DROPEO.Categoria C ON C.nombre = PRODUCTO_CATEGORIA
WHERE PRODUCTO_CATEGORIA IS NOT NULL AND PRODUCTO_SUB_CATEGORIA IS NOT NULL

INSERT INTO EL_DROPEO.Producto(nombre, descricion, precio, marca_id, sub_categoria_id) --Typo
SELECT DISTINCT PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, M.id, S.id
FROM gd_esquema.Maestra 
LEFT JOIN EL_DROPEO.Marca M ON M.nombre = PRODUCTO_MARCA
LEFT JOIN EL_DROPEO.Sub_Categoria S on S.nombre = PRODUCTO_SUB_CATEGORIA
WHERE PRODUCTO_NOMBRE IS NOT NULL AND PRODUCTO_DESCRIPCION IS NOT NULL AND PRODUCTO_PRECIO IS NOT NULL

INSERT INTO EL_DROPEO.Promocion(codigo, descripcion, fecha_inicio, fecha_fin) -- Usar codigo como id
SELECT DISTINCT PROMO_CODIGO, PROMOCION_DESCRIPCION, PROMOCION_FECHA_INICIO, PROMOCION_FECHA_FIN
FROM gd_esquema.Maestra
WHERE PROMO_CODIGO IS NOT NULL

INSERT INTO EL_DROPEO.Regla(descripcion, cantidad_aplicable_descuento, cantidad_aplicable_regla, cantidad_maxima, misma_marca, mismo_producto, promocion_id)
SELECT DISTINCT REGLA_DESCRIPCION, REGLA_CANT_APLICA_DESCUENTO, REGLA_CANT_APLICABLE_REGLA, REGLA_CANT_MAX_PROD, REGLA_APLICA_MISMA_MARCA, REGLA_APLICA_MISMO_PROD, P.id
FROM gd_esquema.Maestra
LEFT JOIN EL_DROPEO.Promocion P on P.codigo = PROMO_CODIGO
WHERE REGLA_DESCRIPCION IS NOT NULL

INSERT INTO EL_DROPEO.Promocion_Producto(producto_id, promocion_id)
SELECT DISTINCT P.id, Promo.id
FROM EL_DROPEO.Producto P
LEFT JOIN EL_DROPEO.Marca M ON M.id = P.marca_id
LEFT JOIN EL_DROPEO.Sub_Categoria S ON S.id = P.sub_categoria_id
LEFT JOIN gd_esquema.Maestra Maestra ON Maestra.PRODUCTO_NOMBRE = P.nombre AND Maestra.PRODUCTO_MARCA = M.nombre AND PRODUCTO_SUB_CATEGORIA = S.nombre
INNER JOIN EL_DROPEO.Promocion Promo ON Maestra.PROMO_CODIGO = Promo.id
WHERE Maestra.PROMO_CODIGO IS NOT NULL AND Maestra.PRODUCTO_NOMBRE IS NOT NULL

INSERT INTO EL_DROPEO.Medio_De_Pago(descripcion, tipo_pago)
SELECT DISTINCT PAGO_MEDIO_PAGO, PAGO_TIPO_MEDIO_PAGO
FROM gd_esquema.Maestra
WHERE PAGO_MEDIO_PAGO IS NOT NULL AND PAGO_TIPO_MEDIO_PAGO IS NOT NULL

INSERT INTO EL_DROPEO.Descuentos(codigo, descripcion, fecha_inicio, fecha_fin, monto, tope, medio_de_pago_id)
SELECT DISTINCT DESCUENTO_CODIGO, DESCUENTO_DESCRIPCION, DESCUENTO_FECHA_INICIO, DESCUENTO_FECHA_FIN, DESCUENTO_PORCENTAJE_DESC, DESCUENTO_TOPE, M.id
FROM gd_esquema.Maestra
LEFT JOIN EL_DROPEO.Medio_De_Pago M ON M.descripcion = PAGO_MEDIO_PAGO AND M.tipo_pago = PAGO_TIPO_MEDIO_PAGO
WHERE DESCUENTO_CODIGO IS NOT NULL
