CREATE SCHEMA EL_DROPEO_UNA_TABLA_DESNORMALIZADA
GO

CREATE PROCEDURE EL_DROPEO_UNA_TABLA_DESNORMALIZADA.MIGRACION AS BEGIN

CREATE TABLE test(
	id int not null identity(1,1) primary key,
	nombre nvarchar(255) not null
)

END
