IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND object_id = OBJECT_ID(N'[EL_DROPEO].[MIGRACION]'))
DROP PROCEDURE EL_DROPEO.MIGRACION
GO

IF EXISTS (SELECT * FROM sys.schemas WHERE name = 'EL_DROPEO')
DROP SCHEMA EL_DROPEO
GO

CREATE SCHEMA EL_DROPEO

GO

CREATE PROCEDURE EL_DROPEO.MIGRACION AS BEGIN

/*
 Creación de tablas
*/

CREATE TABLE EL_DROPEO.Provincia(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL
)

CREATE TABLE EL_DROPEO.Localidad(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL,
	provincia_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Provincia
)

CREATE TABLE EL_DROPEO.Ubicacion(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	calle NVARCHAR(255) NOT NULL,
	altura INT NOT NULL,
	localidad_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Localidad
)

CREATE TABLE EL_DROPEO.Supermercado(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL,
	razon_social NVARCHAR(255) NOT NULL,
	cuit INT NOT NULL UNIQUE,
	iibb INT NOT NULL,
	ubicacion_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Ubicacion
)

CREATE TABLE EL_DROPEO.Sucursal(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ubicacion_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Ubicacion,
	supermercado_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Supermercado
)

CREATE TABLE EL_DROPEO.Tipo_Caja(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	descripcion NVARCHAR(255) NOT NULL,
)

CREATE TABLE EL_DROPEO.Caja(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	tipo_caja_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Tipo_Caja,
	sucursal_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Sucursal
)

CREATE TABLE EL_DROPEO.Cliente(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL,	
	apellido NVARCHAR(255) NOT NULL,
	dni INT NOT NULL UNIQUE,
	fecha_registro DATETIME,
	telefono INT,
	mail NVARCHAR(255),
	fecha_nacimiento DATE,
	ubicacion_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Ubicacion
)

CREATE TABLE EL_DROPEO.Comprobante(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	tipo_comprobante NVARCHAR(255) NOT NULL,
)

CREATE TABLE EL_DROPEO.Empleado(
	legajo INT NOT NULL PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL,
	apellido NVARCHAR(255) NOT NULL,
	dni INT NOT NULL UNIQUE,
	fecha_registro DATETIME,
	sucursal_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Sucursal,
	telefono INT,
	mail NVARCHAR(255),
	fecha_nacimiento DATE
)

CREATE TABLE EL_DROPEO.Ventas(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha DATETIME NOT NULL,
	comprobante_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Comprobante,
	caja_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Caja,
	empleado_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Empleado
)

CREATE TABLE EL_DROPEO.Medio_De_Pago(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	descripcion NVARCHAR(255) NOT NULL
)

CREATE TABLE EL_DROPEO.Detalle(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	cliente_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Cliente,
	numero_tarjeta INT NOT NULL,
	vencimiento_tarjeta DATE NOT NULL,
	cuotas INT NOT NULL
)

CREATE TABLE EL_DROPEO.Pagos(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha DATETIME NOT NULL,
	importe DECIMAL(18, 2) NOT NULL,
	venta_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Ventas,
	medio_de_pago_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Medio_De_Pago,
	detalle_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Detalle
)

CREATE TABLE EL_DROPEO.Descuentos(
	codigo INT NOT NULL PRIMARY KEY,
	descripcion NVARCHAR(255) NOT NULL,
	fecha_inicio DATETIME NOT NULL,
	fecha_fin DATETIME NOT NULL,
	monto DECIMAL(18, 2) NOT NULL,
	tope DECIMAL(18, 2) NOT NULL,
	medio_de_pago_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Medio_De_Pago
)

CREATE TABLE EL_DROPEO.Marca(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL
)

CREATE TABLE EL_DROPEO.Categoria(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL
)

CREATE TABLE EL_DROPEO.Sub_Categoria(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	categoria_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Categoria,
	nombre NVARCHAR(255) NOT NULL
)

CREATE TABLE EL_DROPEO.Producto(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre NVARCHAR(255) NOT NULL,
	descricion NVARCHAR(255) NOT NULL, --Typo
	precio DECIMAL(18, 2) NOT NULL,
	marca_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Marca,
	sub_categoria_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Sub_Categoria
)

CREATE TABLE EL_DROPEO.Item(
	venta_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Ventas,
	producto_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Producto,
	cantidad INT NOT NULL,
	precio_unitario DECIMAL(18, 2) NOT NULL,
	PRIMARY KEY(venta_id, producto_id)
)

CREATE TABLE EL_DROPEO.Promocion(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	codigo INTEGER NOT NULL,
	descripcion NVARCHAR(255) NOT NULL,
	fecha_inicio DATETIME NOT NULL,
	fecha_fin DATETIME NOT NULL,
)

CREATE TABLE EL_DROPEO.Regla(
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	descripcion NVARCHAR(255) NOT NULL,
	cantidad_aplicable_descuento DECIMAL(18, 2) NOT NULL,
	cantidad_aplicable_regla INT NOT NULL,
	cantidad_maxima INT NOT NULL,
	misma_marca BIT NOT NULL,
	mismo_producto BIT NOT NULL,
	promocion_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Promocion
)

CREATE TABLE EL_DROPEO.Promocion_Producto(
	promocion_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Promocion,
	producto_id INT NOT NULL FOREIGN KEY REFERENCES EL_DROPEO.Producto,
	PRIMARY KEY(promocion_id, producto_id)
)


-- Fin de creacion de tablas

-- Inicio de Migracion

INSERT INTO EL_DROPEO.Marca(nombre)
SELECT DISTINCT PRODUCTO_MARCA
FROM gd_esquema.Maestra
WHERE PRODUCTO_MARCA IS NOT NULL

INSERT INTO EL_DROPEO.Categoria(nombre)
SELECT DISTINCT PRODUCTO_CATEGORIA
FROM gd_esquema.Maestra
WHERE PRODUCTO_CATEGORIA IS NOT NULL

INSERT INTO EL_DROPEO.Sub_Categoria(nombre, categoria_id)
SELECT DISTINCT PRODUCTO_SUB_CATEGORIA, C.id
FROM gd_esquema.Maestra
LEFT JOIN EL_DROPEO.Categoria C ON C.nombre = PRODUCTO_CATEGORIA
WHERE PRODUCTO_CATEGORIA IS NOT NULL AND PRODUCTO_SUB_CATEGORIA IS NOT NULL

INSERT INTO EL_DROPEO.Producto(nombre, descricion, precio, marca_id, sub_categoria_id) --Typo
SELECT DISTINCT PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, M.id, S.id
FROM gd_esquema.Maestra 
LEFT JOIN EL_DROPEO.Marca M ON M.nombre = PRODUCTO_MARCA
LEFT JOIN EL_DROPEO.Sub_Categoria S on S.nombre = PRODUCTO_SUB_CATEGORIA
WHERE PRODUCTO_NOMBRE IS NOT NULL AND PRODUCTO_DESCRIPCION IS NOT NULL AND PRODUCTO_PRECIO IS NOT NULL

INSERT INTO EL_DROPEO.Promocion(codigo, descripcion, fecha_inicio, fecha_fin)
SELECT DISTINCT PROMO_CODIGO, PROMOCION_DESCRIPCION, PROMOCION_FECHA_INICIO, PROMOCION_FECHA_FIN
FROM gd_esquema.Maestra
WHERE PROMO_CODIGO IS NOT NULL

INSERT INTO EL_DROPEO.Regla(descripcion, cantidad_aplicable_descuento, cantidad_aplicable_regla, cantidad_maxima, misma_marca, mismo_producto, promocion_id)
SELECT DISTINCT REGLA_DESCRIPCION, REGLA_CANT_APLICA_DESCUENTO, REGLA_CANT_APLICABLE_REGLA, REGLA_CANT_MAX_PROD, REGLA_APLICA_MISMA_MARCA, REGLA_APLICA_MISMO_PROD, P.id
FROM gd_esquema.Maestra
LEFT JOIN EL_DROPEO.Promocion P on P.codigo = PROMO_CODIGO
WHERE REGLA_DESCRIPCION IS NOT NULL


END

-- Fin Migraciones
EXEC EL_DROPEO.MIGRACION

SELECT * FROM EL_DROPEO.Regla

